//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Domain.Common;

namespace Domain.School {
    using System;
    using System.Collections.Generic;

    public partial class AcademicYear : IEntity, ITrackable {
        public AcademicYear() {
            this.IsCurrent = false;
            this.AcademicTerms = new HashSet<AcademicTerm>();
            this.Students = new HashSet<Student>();
            this.Attendances = new HashSet<Attendance>();
            this.TeacherClassSubjectMaps = new HashSet<TeacherClassSubjectMap>();
        }

        public int Id { get; set; }
        public int StartMon { get; set; }
        public int EndMon { get; set; }
        public int StartYear { get; set; }
        public int EndYear { get; set; }
        public DateTime? DeletedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Label { get; set; }
        public bool IsCurrent { get; set; }

        public virtual ICollection<AcademicTerm> AcademicTerms { get; set; }
        public virtual ICollection<Student> Students { get; set; }
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual ICollection<TeacherClassSubjectMap> TeacherClassSubjectMaps { get; set; }

        public static AcademicYear CreateAcademicYear(int startYear) {
            return new AcademicYear {
                StartMon = 4,
                StartYear = startYear,
                EndMon = 3,
                EndYear = startYear + 1, Label = string.Format("{0}-{1}", startYear, startYear + 1)

            };
        }

    }
}
