//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using Domain.Common;

namespace Domain.School {
    using System;
    using System.Collections.Generic;

    public partial class ActivityGrade : IEntity, ITrackable {
        public ActivityGrade() {
            this.DescriptiveIndicators = new HashSet<DescriptiveIndicator>();
        }

        public int Id { get; set; }
        [MaxLength]
        public string Grade { get; set; }
        [MaxLength]
        public string DisplayText { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public DateTime? DeletedDate { get; set; }

        public virtual Activity Activity { get; set; }
        public virtual ICollection<DescriptiveIndicator> DescriptiveIndicators { get; set; }
        public virtual Student Student { get; set; }
        public virtual AcademicTerm AcademicTerm { get; set; }
    }
}
