//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using Domain.Common;

namespace Domain.School {
    using System;
    using System.Collections.Generic;

    public partial class Activity : IEntity, ITrackable {
        public Activity() {
            this.Classes = new HashSet<Class>();
            this.DescriptiveIndicators = new HashSet<DescriptiveIndicator>();
            this.ActivityGrades = new HashSet<ActivityGrade>();
            this.Teachers = new HashSet<Teacher>();
            this.TeacherClassSubjectMaps = new HashSet<TeacherClassSubjectMap>();
            this.Students = new HashSet<Student>();
            this.ActivityResults = new HashSet<ActivityResult>();
        }

        public int Id { get; set; }
        [MaxLength]
        public string Name { get; set; }
        public DateTime? DeletedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int? DisplayOrder { get; set; }
        public bool Optional { get; set; }
        [MaxLength]
        public string CBSECode { get; set; }
        [MaxLength]
        public string CBSEName { get; set; }

        public virtual ICollection<Class> Classes { get; set; }
        public virtual ICollection<DescriptiveIndicator> DescriptiveIndicators { get; set; }
        public virtual ScholasticSection ScholasticSection { get; set; }
        public virtual ICollection<ActivityGrade> ActivityGrades { get; set; }
        public virtual ICollection<Teacher> Teachers { get; set; }
        public virtual ICollection<TeacherClassSubjectMap> TeacherClassSubjectMaps { get; set; }
        public virtual ICollection<Student> Students { get; set; }
        public virtual ICollection<Student> StudentsIgnoringActivity { get; set; }
        public virtual ICollection<ActivityResult> ActivityResults { get; set; }
    }
}
