//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behaviour in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Domain.Common;

namespace Domain.School {
    using System;
    using System.Collections.Generic;

    public partial class AssessmentSchema : IEntity, ITrackable {
        public AssessmentSchema() {
            this.Exams = new HashSet<Exam>();
            this.ClassLabels = new HashSet<ClassLabel>();
        }

        public int Id { get; set; }
        [MaxLength]
        public string Name { get; set; }
        public int Type { get; set; }
        public decimal Weightage { get; set; }
        public DateTime? DeletedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int? StartMonth { get; set; }
        public int? EndMonth { get; set; }
        public int Value { get; set; }
        [ForeignKey("AcademicTerm")]
        public int AcademicTerm_Id { get; set; }
        public virtual AcademicTerm AcademicTerm { get; set; }
        public virtual ICollection<Exam> Exams { get; set; }
        public virtual ICollection<ClassLabel> ClassLabels { get; set; }
    }
}
