//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using Domain.Common;

namespace Domain.School {
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ClassLabel : IEntity, ITrackable {
        public ClassLabel() {
            this.Classes = new HashSet<Class>();
            this.AssessmentSchemas = new HashSet<AssessmentSchema>();
        }

        public int Id { get; set; }
        [MaxLength]
        [Column("Name")]
        public string RomanName { get; set; }
               
        public DateTime? DeletedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int NumericCode { get; set; }
        

        public virtual ICollection<Class> Classes { get; set; }
        public virtual ICollection<AssessmentSchema> AssessmentSchemas { get; set; }
    }
}
