//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using Domain.Common;

namespace Domain.School {
    using System;
    using System.Collections.Generic;

    public partial class DescriptiveIndicator : IEntity, ITrackable {
        public DescriptiveIndicator() {
            Activities = new HashSet<Activity>();
            ActivityGrades = new HashSet<ActivityGrade>();
            ActivityResults = new HashSet<ActivityResult>();
        }

        public int Id { get; set; }

        [MaxLength]
        public string Category { get; set; }

        [MaxLength]
        public string Text { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public DateTime? DeletedDate { get; set; }
        public int? DisplayOrder { get; set; }
        // add min max for point wise pick the indicators
        public decimal? Min { get; set; }
        public decimal? Max { get; set; }
        [MaxLength]
        public string ShortDescription { get; set; }
        
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual ICollection<ActivityGrade> ActivityGrades { get; set; }
        public virtual ICollection<ActivityResult> ActivityResults { get; set; }
    }
}
