//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using Domain.Common;

namespace Domain.School {
    using System;
    using System.Collections.Generic;

    public partial class ExamGradingSchema : IEntity, ITrackable {
        public int Id { get; set; }
        public decimal LowMarks { get; set; }
        public decimal HighMarks { get; set; }
        [MaxLength]
        public string Grade { get; set; }
        public decimal? GradePoint { get; set; }
        public int GradeType { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public DateTime? DeletedDate { get; set; }
    }
}
