//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Domain.Common;


namespace Domain.School
{
    using System;
    using System.Collections.Generic;

    public partial class Exam : IEntity, ITrackable
    {
        public Exam()
        {
            this.Weightage = 100m;
            this.ExamResults = new HashSet<ExamResult>();
            this.Classes = new HashSet<Class>();
        }
        [Key]
        public int Id { get; set; }
        public DateTime? ExamDate { get; set; }
        public decimal MaximumMarks { get; set; }
        public decimal Weightage { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public DateTime? DeletedDate { get; set; }
        [MaxLength]
        public string Name { get; set; }

        [ForeignKey("AssesmentSchema")]
        public int AssesmentSchema_Id { get; set; }
        public virtual AssessmentSchema AssesmentSchema { get; set; }
        public virtual ICollection<ExamResult> ExamResults { get; set; }
        [ForeignKey("Subject")]
        public int Subject_Id { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual ICollection<Class> Classes { get; set; }
        public virtual ICollection<ExamSection> ExamSections { get; set; }
    }
}
