//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Domain.Common;

namespace Domain.School {
    using System;
    using System.Collections.Generic;

    public partial class ExamResult : IEntity, ITrackable {
        public int Id { get; set; }
        public decimal Marks { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public DateTime? DeletedDate { get; set; }
        [MaxLength]
        public string Remarks { get; set; }
        public short? ApprovedBy { get; set; }
        [ForeignKey("Exam")]
        public int Exam_Id { get; set; }
        public virtual Exam Exam { get; set; }
        [ForeignKey("Student")]
        public int Student_Id { get; set; }
        public virtual Student Student { get; set; }
    }
}
