//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using Domain.Common;

namespace Domain.School {
    using System;
    using System.Collections.Generic;

    public partial class SectionLabel : IEntity, ITrackable {
        public SectionLabel() {
            this.Classes = new HashSet<Class>();
        }

        public int Id { get; set; }
        [MaxLength]
        [Required]
        public string Name { get; set; }
        
        public DateTime? DeletedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public System.DateTime CreatedDate { get; set; }

        public virtual ICollection<Class> Classes { get; set; }
    }
}
