//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using Domain.Common;

namespace Domain.School {
    using System;
    using System.Collections.Generic;

    public partial class SmsCampaign : IEntity, ITrackable {
        public SmsCampaign() {
            this.SmsReports = new HashSet<SmsReport>();
            this.Students = new HashSet<Student>();
            this.Teacher = new HashSet<Teacher>();
        }

        public int Id { get; set; }
        [MaxLength]
        public string Message { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public DateTime? DeletedDate { get; set; }

        public virtual ICollection<SmsReport> SmsReports { get; set; }
        public virtual ICollection<Student> Students { get; set; }
        public virtual ICollection<Teacher> Teacher { get; set; }
    }
}
