//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using Domain.Common;

namespace Domain.School {
    using System;

    public class SmsReport : IEntity, ITrackable {
        public int Id { get; set; }
        public DateTime SendDate { get; set; }
        public DateTime DeliveryDate { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public DateTime? DeletedDate { get; set; }
        public string SmsShortCode { get; set; }
        public string MobileNo { get; set; }
        [MaxLength]
        [Required]
        public string Message { get; set; }
        public string SenderId { get; set; }
        public bool Status { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual Student Student { get; set; }
    }
}
