CREATE TABLE [dbo].[Teachers] (
    [Id]            INT            IDENTITY (1, 1) NOT NULL,
    [DeletedDate]   DATETIME       NULL,
    [ModifiedDate]  DATETIME       NULL,
    [CreatedDate]   DATETIME       NOT NULL,
    [UserId]        NVARCHAR (MAX) NULL,
    [UserName]      NVARCHAR (MAX) NULL,
    [FirstName]     NVARCHAR (MAX) NULL,
    [LastName]      NVARCHAR (MAX) NULL,
    [DOB]           DATETIME       DEFAULT ('1900-01-01T00:00:00.000') NOT NULL,
    [Gender]        BIT            NULL,
    [MotherName]    NVARCHAR (MAX) NULL,
    [FatherName]    NVARCHAR (MAX) NULL,
    [PhoneNo]       NVARCHAR (MAX) NULL,
    [MobileNo]      NVARCHAR (MAX) NULL,
    [EmailId]       NVARCHAR (MAX) NULL,
    [Nationality]   NVARCHAR (MAX) NULL,
    [StreetAddress] NVARCHAR (MAX) NULL,
    [City]          NVARCHAR (MAX) NULL,
    [State]         NVARCHAR (MAX) NULL,
    [Country]       NVARCHAR (MAX) NULL,
    [PinCode]       NVARCHAR (MAX) NULL,
    [Qualification] NVARCHAR (MAX) NULL,
    [ImagePath]     NVARCHAR (MAX) NULL,
    [JoiningDate]   DATETIME       NULL,
    [EmployeeId]    NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_dbo.Teachers] PRIMARY KEY CLUSTERED ([Id] ASC)
);

